resources:
- name: lf-git
  type: git
  source:
    uri: https://github.com/pivotal/LicenseFinder
    branch: master

- name: lf-image
  type: docker-image
  source:
    repository: licensefinder/license_finder
    email: ((LicenseFinderDockerEmail))
    username: ((LicenseFinderDockerUserName))
    password: ((LicenseFinderDockerPassword))

jobs:
- name: docker
  plan:
  - get: lf-git
  - put: lf-image
    params:
     build: lf-git

- name: build-push-gem
  plan:
  - aggregate:
    - get: lf-git
    - get: lf-image
  - task: run rake
    image: lf-image
    params:
      GEM_API_KEY: ((LicenseFinderGemApiKey))
    config:
      platform: linux
      inputs:
      - name: lf-git
      run:
        path: bash
        args:
        - "-lc"
        - ./LicenseFinder/ci/scripts/pushscript.sh