resources:
- name: LicenseFinder
  type: git
  source:
    uri: https://github.com/pivotal/LicenseFinder
    branch: master

- name: image
  type: docker-image
  source:
    repository: licensefinder/license_finder
    email: ((LicenseFinderDockerEmail))
    username: ((LicenseFinderDockerUserName))
    password: ((LicenseFinderDockerPassword))

jobs:
- name: docker
  plan:
  - get: LicenseFinder
  - put: image
    params:
     build: LicenseFinder

- name: build-push-gem
  plan:
  - aggregate:
    - get: LicenseFinder
    - get: image
  - task: run rake
    image: image
    params:
      GEM_API_KEY: ((LicenseFinderGemApiKey))
    config:
      platform: linux
      inputs:
      - name: LicenseFinder
      run:
        path: bash
        args:
        - "-lc"
        - ./LicenseFinder/ci/scripts/pushscript.sh