AllCops:
  TargetRubyVersion: 2.3.3 
  Exclude:
    - 'lib/license_finder/reports/**/*'
    - 'features/fixtures/**/*'
    - 'releases/**/*'
    - 'ci/**/*'
    - 'tmp/**/*'
    - 'Gemfile'

#Layout Cops
HeredocIndentation:
  Enabled: false
EmptyLinesAroundArguments:
  Enabled: false

#Linting Cops
AmbiguousRegexpLiteral:
  Enabled: false

# Metrics Cops
AbcSize:
  Max: 35
BlockLength:
  Enabled: false # TODO: enable and refactor long methods
#  ExcludedMethods: ['describe', 'context', 'it', 'shared_examples']  # uncomment once enabled
ClassLength:
  Enabled: false
CyclomaticComplexity:
  Max: 15
PerceivedComplexity:
  Max: 15
LineLength:
  Max: 200
MethodLength:
  Enabled: false
ModuleLength:
  Enabled: false

# Security Cops
YAMLLoad:
  Enabled: false

#Style Cops
Style/MethodMissingSuper:
  Enabled: false
Style/MissingRespondToMissing:
  Enabled: false
Style/FormatStringToken:
  EnforcedStyle: unannotated
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Layout/MultilineMethodCallIndentation:
    Enabled: false
DoubleNegation:
  Enabled: false
Documentation:
  Enabled: false
FileName:
  Exclude:
    - '**/Rakefile'
    - '**/Gemfile'
    - '**/Podfile'
ModuleFunction:
  Enabled: false
  EnforcedStyle: extend_self
