#!/bin/bash
if `which docker > /dev/null`; then
	DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
	if [ $# -eq 0 ]; then
  		docker run -v $DIR:/scan -it licensefinder/license_finder /bin/bash -lc "cd /scan && /bin/bash -l"
	else
  		docker run -v $DIR:/scan -it licensefinder/license_finder /bin/bash -lc "cd /scan && bundle install && `echo $@`"
	fi
else
  echo "You do not have docker installed. Please install it:"
  echo "    https://docs.docker.com/engine/installation/"
  exit 1
fi
