#!/bin/bash
if `which docker > /dev/null`; then
	if [ $# -eq 0 ]; then
  		docker run -v $PWD:/scan -it licensefinder/license_finder
	else
  		docker run -v $PWD:/scan -it licensefinder/license_finder /bin/bash -lc "cd /scan && `echo $@`"
	fi
else
  echo "You do not have docker installed. Please install it:"
  echo "    https://docs.docker.com/engine/installation/"
  exit 1
fi
