PROJECT = license_finder_noop_library
PROJECT_DESCRIPTION = OTP noop library bootstrapped with Erlang.mk
PROJECT_VERSION = 0.1.0

# GitHub dep with many different licenses & sub-dependencies
DEPS = rabbitmq_management
dep_rabbitmq_management = git https://github.com/rabbitmq/rabbitmq-management.git master

include erlang.mk
