---
image_resource:
  type: docker-image
  source:
    repository: brenix/alpine-bash-git-ssh
    tag: latest
platform: linux
inputs:
- name: lf-git-version
- name: lf-release
- name: semver-version
outputs:
- name: lf-git-changed
- name: version
run:
  path: lf-git-version/ci/scripts/updateChangelog.sh
