resources:
- name: LicenseFinder
  type: git
  source:
    uri: https://github.com/joemoore/LicenseFinder.git
    branch: aggregate

jobs:
- name: ruby-2-3-0
  plan:
  - get: LicenseFinder
    trigger: false
  - task: test1
    file: LicenseFinder/build.yml
    params:
      RUBY_VERSION: 2.3.0

- name: ruby-2-2-0
  plan:
  - get: LicenseFinder
    trigger: false
  - task: test1
    file: LicenseFinder/build.yml
    params:
      RUBY_VERSION: 2.2.0

- name: ruby-2-1-5
  plan:
  - get: LicenseFinder
    trigger: false
  - task: test1
    file: LicenseFinder/build.yml
    params:
      RUBY_VERSION: 2.1.5
